
##on : [push]

##on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
##  push:
##    branches:
##      - main

name: azureARMDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps: 

        - name: Login in to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_SECRETS }}

        - name: Checkout Source Code
          uses: actions/checkout@v2

        - name: Azure Cli
          uses: azure/CLI@v1
          with:
            inlineScript: |
              ./azurearmdeployment.sh
